---
- hosts: storage
  gather_facts: no
  tasks:
    - block:
        - name: Add storage label
          k8s: 
            state: present
            context: "{{ ocp_cluster_name }}"
            definition:            
              apiVersion: v1
              kind: Node
              metadata:
                name: "{{ inventory_hostname }}"
                annotations:
                  openshift.io/node-selector: ''
                labels:
                  node-role.kubernetes.io/storage: ""
                  cluster.ocs.openshift.io/openshift-storage: ""                
                  openshift.io/node-selector: "" 
      delegate_to: localhost
- hosts: masters[0]
  gather_facts: no
  tasks:
    - block:
        - name: Create openshift-storage project
          k8s:
            state: present
            context: "{{ ocp_cluster_name }}"        
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
               name: openshift-storage
                labels:
                  openshift.io/cluster-monitoring: "true"
                annotations:
                  openshift.io/node-selector: ""
       delegate_to: localhost
