---
- hosts: masters[0]
  gather_facts: no
  tasks:
    - block:
        - name: Tag default project
          k8s: 
            state: present
            context: "{{ ocp_cluster_name }}"            
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: default
                labels:
                  network.openshift.io/policy-group: ingress
        - name: Create project template
          k8s:
            state: present
            context: "{{ ocp_cluster_name }}"            
            definition: "{{ lookup('file','../files/project-template.yml') }}"
        - name: Configure default project
          k8s:
            state: present
            context: "{{ ocp_cluster_name }}"            
            definition:
              apiVersion: config.openshift.io/v1
              kind: Project
              metadata:
                name: cluster
              spec:
                projectRequestTemplate:
                  name: project-request
      delegate_to: localhost        
              