kind: ConfigMap
apiVersion: v1
metadata:
  name: scheduler-policy
  namespace: openshift-config
data:
  policy.cfg: |
    {
    "kind": "Policy",
    "apiVersion": "v1",
    "priorities": [
        {
            "name":"Region",
            "weight" : 1,
            "argument": {
                "serviceAntiAffinity": {
                    "label": "region"
                    }
               }
           }
       ]
    }
